### ISSUE TITLE
3.0.3 is not support Jdk 10?

### ISSUE THREAD

**Issue by gnimeh** [sbt/sbt-jacoco#111]
### Expected vs Actual Behaviour

I have a play java application, and I used sbt-jacoco 3.0.3 to scan coverage for java code. When I execute sbt test , I have this error:
```
[error] java.io.IOException: Error while instrumenting class Module.class.
[error]         at org.jacoco.core.instr.Instrumenter.instrumentError(Instrumenter.java:166)
[error]         at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:117)
```

And I change my local java env to jdk 8, It works fine. So it means sbt-jacoco 3.0.3 is not support java10 yet?

### Environment

* SBT version:1.1.2
* Plugin version: 3.0.3
* Java version: java 10

**Comment by stringbean** [comment]
It looks like JaCoCo added support for Java 10 in [0.8.1](https://github.com/jacoco/jacoco/releases/tag/v0.8.1) (sbt-jacoco currently uses 0.7.9).

It's looking like support for JaCoCo 0.8 is going to take some time to implement (#106). Sorry if this is a major issue for you.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt-jacoco/pull/119
