### ISSUE TITLE
sbt-jacoco does not work with Java 11

### ISSUE THREAD

**Issue by JJonesAtAvaya** [sbt/sbt-jacoco#118]
### Expected vs Actual Behaviour

It should...

Work with Java 11

Instead it...

Gives errors like this:

[debug] Found jacoco agent: Vector()
[debug] instrumenting /Users/foo/src/abc/foo-api/target/scala-2.12/classes/configurations/CustomObjectMapper.class
[error] java.io.IOException: Error while instrumenting class CustomObjectMapper.class.
[error] 	at org.jacoco.core.instr.Instrumenter.instrumentError(Instrumenter.java:166)
[error] 	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:117)
[error] 	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:136)
[error] 	at com.github.sbt.jacoco.data.InstrumentationUtils$.$anonfun$instrumentClasses$11(InstrumentationUtils.scala:64)
[error] 	at com.github.sbt.jacoco.data.InstrumentationUtils$.$anonfun$instrumentClasses$11$adapted(InstrumentationUtils.scala:61)
[error] 	at resource.AbstractManagedResource.$anonfun$acquireFor$1(AbstractManagedResource.scala:88)

### Steps to Reproduce

try to build a Play Framework app under Java 11 using the sbt-jacoco plugin
```
> jacoco:jacoco
...
```

### Environment

* SBT version: 1.2.6
* Plugin version: 3.1.0
* Scala version(s): _(include all versions if cross-building)_
* Java version: 11
* Link to project source: _(if available)_

**Comment by raphaelNguyen** [comment]
I have this issue as well. I went on jacoco repo and had a look. It seems like that jacoco did not support JDK 11 and they have already released version 0.8.2 which does this (please see jacoco/jacoco#663). Is it possible for sbt-jacoco to use the new version?
