### ISSUE TITLE
Release ETA of version 3.2.0?

### ISSUE THREAD

**Issue by dragonjuggler** [sbt/sbt-jacoco#122]
I'm interested in the 3.2.0 version which will use JaCoCo version 0.8.2.  Is there an expected ETA for this release?  I noticed that the change to upgrade to 0.8.2 was made 3 months ago, but there hasn't been a release since last year.

BTW - I couldn't find another avenue to ask this question.  If I followed the wrong process, what's the right way to do this?

Thanks.

-Mark

**Comment by master-elodin** [comment]
Looks like it's released already: https://bintray.com/stringbean/sbt-plugins/sbt-jacoco/3.2.0

The GitHub page hasn't been updated with the version, though

**Comment by dragonjuggler** [comment]
Interesting.  Since the release did not look the same as the others, with the various tags, I assumed it wasn't "official".  I just tried using it, and ti works.  Thanks!

**Comment by Miuler** [comment]
> Parece que ya se lanzó: https://bintray.com/stringbean/sbt-plugins/sbt-jacoco/3.2.0
> 
> Sin embargo, la página de GitHub no se ha actualizado con la versión

Please sbt-jacoco, update the documentation, and change 3.1 by 3.2 in https://www.scala-sbt.org/sbt-jacoco/
The 3.1 version have issues with java 11 :(

**Comment by eed3si9n** [comment]
3.3.0 is released, and I also updated the doc.
