### ISSUE TITLE
what do the printed stats mean?

### ISSUE THREAD

**Issue by axaluss** [sbt/sbt-jacoco#124]
```
[info] Lines: 56.53% (>= required 50.0%) covered, 306 of 704 missed, OK
[info] Instructions: 36.23% (>= required 20.0%) covered, 5056 of 7929 missed, OK
[info] Branches: 20.82% (>= required 20.0%) covered, 369 of 466 missed, OK
[info] Methods: 39.12% (>= required 20.0%) covered, 207 of 340 missed, OK
[info] Complexity: 25.83% (>= required 20.0%) covered, 425 of 573 missed, OK
[info] Class: 51.46% (>= required 50.0%) covered, 50 of 103 missed, OK
```
What does `Complexity: 25.83%` even mean?

### Expected vs Actual Behaviour

It should explain somewhere what the printed stats even mean.

**Comment by eed3si9n** [comment]
I don't know much about this project but as far as I can tell sbt-jacoco is printing out the information supplied by JaCoCo. The explanation for these metrics I think is available here - https://www.eclemma.org/jacoco/trunk/doc/counters.html

"complexity" here seems to be short for cyclomatic complexity, which measures how branchy/loopy your method implementation is. _Covered_ would mean that the test took those paths, and _missed_ likely indicates that the code paths were _not_ tested?

If you would like to contribute to the documentation, plz send a PR for this file - https://github.com/sbt/sbt-jacoco/blob/master/src/paradox/getting-started.md
