### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jeffrey-aguilera** [sbt/sbt-jacoco#129]
### Expected vs Actual Behaviour

It should...

Instead it...

### Steps to Reproduce

```
> jacoco:jacoco
...
```

### Environment

* SBT version:
* Plugin version:
* Scala version(s): _(include all versions if cross-building)_
* Java version:
* Link to project source: _(if available)_

**Comment by eed3si9n** [comment]
I'm not sure, but I just merged/closed pending PRs.
