### ISSUE TITLE
any plan to upgrade to 0.8.5 (or at least this 0.8.3 where official support for jdk11)  ?

### ISSUE THREAD

**Issue by aamrute-idnow** [sbt/sbt-jacoco#130]
Hi, 
Any plan to update jacoco version ?
Thanks

**Comment by gzoller** [comment]
This is great!  I need 0.8.6 to support JDK > 12 as well.

**Comment by gzoller** [comment]
Just completed a PR that passed that moves to jacoco 0.8.6.  Unfortunately it was too much of a stretch (for me anyway) to maintain support all the way back to pre-1.0 sbt, scala 2.10, etc.  So this standardizes on Scala 2.12.12, Jdk13, and sbt 1.3.4.

**Comment by aamrute-idnow** [comment]
Could someone please merge the PR

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt-jacoco/pull/133
