### ISSUE TITLE
Merged report setting not working 

### ISSUE THREAD

**Issue by samudurand** [sbt/sbt-jacoco#137]
### Expected vs Actual Behaviour

I have been trying to use the `jacocoMergedReportSettings` setting to set the merged threshold but it has no effect. The `jacocoReportSettings` does work as expected.

### Steps to Reproduce

Add the setting `jacocoMergedReportSettings` into a project that has both unit and integration tests

```
    jacocoMergedReportSettings := JacocoReportSettings()
      .withThresholds(
        JacocoThresholds(
          instruction = 80,
          method = 100,
          branch = 100,
          complexity = 100,
          line = 90,
          clazz = 100)
      ),
```
Execute ` sbt clean jacoco it:jacoco`, and check the output:

```
[info] ------- Jacoco Merged Coverage Report -------
[info]
[info] Lines: 32.93% (>= required 0.0%) covered, 279 of 416 missed, OK
[info] Instructions: 4.43% (>= required 0.0%) covered, 26953 of 28201 missed, OK
[info] Branches: 1.71% (>= required 0.0%) covered, 2581 of 2626 missed, OK
[info] Methods: 7.23% (>= required 0.0%) covered, 1514 of 1632 missed, OK
[info] Complexity: 4.05% (>= required 0.0%) covered, 2869 of 2990 missed, OK
[info] Class: 13.11% (>= required 0.0%) covered, 159 of 183 missed, OK
[info]
```
The threshold are clearly not set.

**Comment by eed3si9n** [comment]
I'm not familiar with this plugin, but looking at the source the setting is scoped to `IntegrationTest` https://github.com/sbt/sbt-jacoco/blob/master/src/main/scala/com/github/sbt/jacoco/JacocoItPlugin.scala (although it doesn't have to be), so to rewire it you'd also need to scope it to `IntegrationTest`. Try:

```scala
IntegrationTest / jacocoMergedReportSettings := JacocoReportSettings()
      .withThresholds(
        JacocoThresholds(
          instruction = 80,
          method = 100,
          branch = 100,
          complexity = 100,
          line = 90,
          clazz = 100)
      ),
```

**Comment by samudurand** [comment]
Thanks @eed3si9n ! That was it, the docs are a bit light on settings usages if you are not too familiar with Sbt syntax
