### ISSUE TITLE
Not running @RunWith(MockitoJUnitRunner.class)?

### ISSUE THREAD

**Issue by jhberges** [sbt/sbt-jacoco#15]
I'm wondering if there's something I'm missing out on here...
I've a Mockito JUnit tests that just won't run under the jacoco4sbt managed tests?

Env:
- Play 2.2.1
- Java based app
- jacoco4sbt 2.1.4

Test is using Mockito 1.9.5 annotations:

``` java
@RunWith(MockitoJUnitRunner.class)
public class FacadeTest {
  @Mock
  private Api api;
  @InjectMocks
  private Facade facade;

  @After
  public void after() {
    verifyNoMoreInteractions(api);
  }

  @Test
  public void facade() throws Exception {
  }
}
```

When running `play test`

```
[info] Total for test backend.FacadeTest
[info] Finished in 0.001 seconds
[info] 0 tests, 0 failures, 0 errors
[info] Test ApplicationTest ignored
[info] ApplicationTest
[info] o ApplicationTest
[info]
[info]
[info] Total for test ApplicationTest
[info] Finished in 0.001 seconds
[info] 1 tests, 0 failures, 0 errors
[error] Test backend.FacadeTest.handleConfirmationWhenIgnore failed: java.lang.NullPointerException: null
[error]     at ... backend.FacadeTest.facade(FacadeTest.java:57)
[error]     ...
[info] backend.FacadeTest
[info] x facade
[info]
[info] Total for test backend.FacadeTest
[info] Finished in 0.003 seconds
[info] 2 tests, 1 failures, 0 errors
[error] Failed: Total 45, Failed 1, Errors 0, Passed 42, Skipped 2
```

When running `play jacoco:test`

```
[info] Total for test backend.FacadeTest
[info] Finished in 0.006 seconds
[info] 0 tests, 0 failures, 0 errors
[info] ApplicationTest
[info] Test ApplicationTest ignored
[info] o ApplicationTest
[info]
[info]
[info] Total for test ApplicationTest
[info] Finished in 0.011 seconds
[info] 1 tests, 0 failures, 0 errors
[info] Passed: Total 43, Failed 0, Errors 0, Passed 41, Skipped 2
[success] Total time: 11 s, completed 27.feb.2014 10:00:17
```

The qa.jacoco.sbt is:

```
import de.johoop.jacoco4sbt._
import JacocoPlugin._

//----------------------------------------
// Setup Jacoco test coverage.
// Invocation: jacoco:cover
// Results: target/jacoco/html/index.html
// See: https://github.com/sbt/jacoco4sbt
//      project/plugins.sbt
//----------------------------------------

jacoco.settings

parallelExecution      in jacoco.Config := false

jacoco.outputDirectory in jacoco.Config := file("target/jacoco")

jacoco.reportFormats   in jacoco.Config := Seq(XMLReport("utf-8"), HTMLReport("utf-8"))

jacoco.excludes        in jacoco.Config := Seq("views*", "*Routes*", "controllers*routes*", "controllers*Reverse*", "controllers*javascript*", "controller*ref*")
```

Thanks.

**Comment by madhawa1984** [comment]
Hi, i am using type safe activator for play project with java.
1. SBT VERSION - 0.13.0
2. scala version - 2.10.2
3. play version - 2.2.0 

in the project i am having junit tests which uses mockito only for some test cases. when i run code coverage using jacoco4sbt  2.1.3 i getting coverage reports with 0% for all the test cases.Console shows that the All the test cases are executing when jacoco:cover executed.But Coverage report comes as 0.Hey any one having a solution for me.



check part of my scala build file.
=============================================================================
 val appDependencies = Seq(
    // Add your project dependencies here,
    "com.novocode" % "junit-interface" % "0.10",
    "net.vz.mongodb.jackson" %% "play-mongo-jackson-mapper" % "1.1.0",
    "org.springframework" % "spring-context" % "3.1.2.RELEASE",
    "org.springframework" % "spring-test" % "3.1.2.RELEASE",
    "org.springframework" % "spring-beans" % "3.1.2.RELEASE",
    "org.springframework" % "spring-expression" % "3.1.2.RELEASE",
    "org.mockito" % "mockito-all" % "1.9.5",
    "com.github.mumoshu" %% "play2-memcached" % "0.3.0.2",
    "de.flapdoodle.embed" % "de.flapdoodle.embed.mongo" % "1.36",
    javaCore,
    cache
  )

 lazy val jacoco_settings = Defaults.defaultSettings ++ Seq(jacoco.settings: _*) ++ Seq(
    parallelExecution in jacoco.Config := false,
    Keys.fork in jacoco.Config := false
  )

  conflictManager := ConflictManager.strict

val main = play.Project(appName, appVersion, appDependencies, settings =jacoco_settings).settings(
    resolvers += "Spy Repository" at "http://files.couchbase.com/maven2",
    resolvers += "maven repo" at "http://repo1.maven.org/maven2/",

    javaOptions in Test += "-Dconfig.file=conf/test.conf",   
   
    // this is to get around a play 2.1.3 issue where tests are not run
    // see http://stackoverflow.com/questions/18275638/play-framework-2-1-3-doesnt-run-any-tests
    testOptions in Test ~= { args =>
        for {
          arg <- args
          val ta: Tests.Argument = arg.asInstanceOf[Tests.Argument]
          val newArg = if(ta.framework == Some(TestFrameworks.JUnit)) ta.copy(args = List.empty[String]) else ta
        } yield newArg
      }
   )

}
==================plugins.sbt===================================================
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.0")

addSbtPlugin("de.johoop" % "jacoco4sbt" % "2.1.3")
=============================================================================
