### ISSUE TITLE
New release for JaCoCo 0.8.11 adding JDK 21 support

### ISSUE THREAD

**Issue by ane** [sbt/sbt-jacoco#289]
Java 21 LTS was released on September 19th, 2023. Support for it in JaCoCo was added in version 0.8.11, and [looks like the version is already correct in sbt-jacoco](https://github.com/sbt/sbt-jacoco/blob/main/build.sbt#L1), all that's missing is someone pushing a new version to Sonatype Nexus.

**Comment by DrSatyr** [comment]
Seems Jacoco just turned off JDK 21 support in the current version (see PR https://github.com/jacoco/jacoco/pull/1433/files) due to an issue in Scala: https://github.com/jacoco/jacoco/issues/1431

We need to wait for a fix in a further version of Jacopo.

**Comment by jxnu-liguobin** [comment]
What state about this issue?

**Comment by eed3si9n** [comment]
I don't use this plugin or send PRs, but apparently I've been the person cutting a release, so I'm doing it now.

**Comment by eed3si9n** [comment]
Release failed (https://github.com/sbt/sbt-jacoco/actions/runs/8250879513/job/22566565806), but something I can fix.

**Comment by eed3si9n** [comment]
Released https://github.com/sbt/sbt-jacoco/releases/tag/v3.5.0
