### ISSUE TITLE
jacoco:test runs in root working directory for sub projects instead of the current sub project's directory

### ISSUE THREAD

**Issue by muymoo** [sbt/sbt-jacoco#3]
I am using Play 2.2.1 and jacoco4sbt 2.1.2
## Short version:

`play test` execute common subproject tests' `FakeApplication()` in the sub project's directory. `play jacoco:test` executes this `FakeApplication()` in the root directory.
## Long version:

I am trying to read the root's configuration file in my common subproject FakeApplication by running as:

``` java
app  = FakeApplication(new File("./../../", ...)
```

This accesses the app.conf fine with `play test`. But with `jacoco:test` I get the following error:

<pre>Error while writing configuration file /path/to/root/./../../conf/app.conf
org.apache.commons.configuration.ConfigurationException: No file name has been set!
</pre>

If I change my FakeApplication to 

``` java
app = FakeApplication(new File("."), ...)
```

`jacoco:test` works, but `play test` fails with:

<pre>
Error while writing configuration file /path/to/root/modules/common/./conf/app.conf for property...
org.apache.commons.configuration.ConfigurationException: No file name has been set!
</pre>

Note the difference between 
jacoco:test: `/path/to/root/./../../conf/app.conf`
and
play test: `/path/to/root/modules/common/./conf/app.conf`

I have a multi project setup that looks like this:

<pre>
root
- app
- conf
- project 
   - Build.scala
   - plugins.sbt
- modules
   - api
   - common
      - app
      - test
      - conf
   - etc...
</pre>

My Build.scala looks like:

``` scala
  // So we can get code coverage
  lazy val jacocoSettings = Seq(
      parallelExecution in jacoco.Config := false,
      jacoco.excludes in jacoco.Config := Seq("Routes*","*Reverse*","*anonfun*"),
      resolvers += "julienrf.github.com" at "http://julienrf.github.com/repo/"
    )

  // Every module needs to have jacoco (for coverage)
  lazy val s = playJavaSettings ++ Seq(jacoco.settings:_*) ++ jacocoSettings

  lazy val common = play.Project(
      "common", appVersion, commonDependencies, settings = s, path = file("modules/common")
    ).dependsOn(api)
```

I've tried setting the `baseDirectory in jacoco.Config` to the sub project path, but that doesn't work either.

I would expect that `jacoco:test` executes the sub project tests in the sub project's working directory.

This was working with Play 2.1.3 and jacoco.

**Comment by subratmohapatra2005** [comment]
@muymoo @ rmmeans - Can you please update the thread with an working example of build.scala. As we are also facing a similar problem
