### ISSUE TITLE
Jacoco do not include unmanaged resource into classpath

### ISSUE THREAD

**Issue by fcappi** [sbt/sbt-jacoco#58]
This causes getClass().getClassLoader().getResource("resource_name.conf") to fail when running jacoco:cover

**Comment by fedork** [comment]
Is there a workaround for this?

**Comment by stringbean** [comment]
@fcappi & @fedork: can you try this with sbt-jacoco 3.0.2? The `jacoco` configuration has been removed so it _should_ pick up the resources without any issues.

**Comment by chadselph** [comment]
it's not working for in 3.0.3, but I'm open to the possibility I've done something wrong.

I'm just using the default `src/test/resources/...` location; the tests work with `sbt test` but when running `sbt jacoco` it can't find the files.
