### ISSUE TITLE
Random coverage in multi-project

### ISSUE THREAD

**Issue by checat** [sbt/sbt-jacoco#66]
I've converted a mixed Java/Scala project into multi-project build, where
- root-project aggregates java-project, scala-project
- scala-project dependsOn java-project

When I run jacoco:cover on this project, it produces indeterministic coverage (lower than actual) when run as:
`sbt clean test jacoco:cover`
`sbt clean jacoco:cover jacoco:cover`
But if run immediately after clean
`sbt clean jacoco:cover`
or if run separately
`sbt java-project/jacoco:cover scala-project/jacoco:cover`
then coverage is correct and deterministic.

The visible difference is that in correct cases tests are not run in parallel.

I've tried jacoco4sbt 2.1.6 and 2.2.0

**Comment by checat** [comment]
Workaround is `parallelExecution in Global := false`
Any of `parallelExecution := false`, `parallelExecution in Test := false`, `parallelExecution in jacoco.Config := false` do not help, jacoco:check is still run in parallel.

**Comment by ravikiran1729** [comment]
I had a similar issue, and once i placed "parallelExecution in Global := false" in sbt, all my testcases worked properly. Thanks a ton.... :) Cheers.

**Comment by UnknownNPC** [comment]
Plus one for `parallelExecution in Global := false`. (y)

**Comment by stringbean** [comment]
@checat can you please try with `sbt-jacoco` 3.0.2 and see if this fixes the issue?

**Comment by checat** [comment]
Will try on next week

**Comment by checat** [comment]
Quick test on one of projects shows that bug has gone in 3.0.2
