### ISSUE TITLE
Make plugin work with forked tests

### ISSUE THREAD

**Issue by jmhofer** [sbt/sbt-jacoco#9]
As sbt has been supporting forked tests for quite a while now, jacoco4sbt should too.

There's two possibilities to implement this: Either use the JaCoCo Java agent for everything except merging and reporting, or pre-instrument and adapt the classpath (as done currently).

Handling forked tests should actually be easier than handling non-forked tests afaik...

**Comment by subratmohapatra2005** [comment]
@jmhofer Does this help merging the unit tests across multiple modules in a play project into one merged report? If yes, can you please share a working example of build.scala
