### ISSUE TITLE
jacocoExcludes not working

### ISSUE THREAD

**Issue by erikthered** [sbt/sbt-jacoco#96]
### Expected vs Actual Behaviour

Previously when the plugin was still jacoco4sbt (2.3.0), I had the following exclusions and it seemed to work fine:
```
jacoco.excludes in jacoco.Config := Seq(
  "controllers.Reverse*",
  "controllers.javascript.*",
  "jooq.*",
  "Module",
  "router.Routes*",
  "*.routes*"
)
```

I switched it to the following, and now it doesn't seem to be excluding anything:
```
jacocoExcludes := Seq(
  "controllers.Reverse*",
  "controllers.javascript.*",
  "jooq.*",
  "Module",
  "router.Routes*",
  "*.routes*"
)
```

### Steps to Reproduce

Add to plugins.sbt
```
addSbtPlugin("com.github.sbt" % "sbt-jacoco" % "3.0.2")
```

Run tasks
```
sbt clean test jacocoReport
```

### Environment

* SBT version: 1.0.2
* Plugin version: 3.0.2
* Scala version(s): 2.12.2
* Java version: 1.8.0_144
* Link to project source: N/A

**Comment by stringbean** [comment]
Can you try changing it to:

```scala
jacocoExcludes in Test := Seq(
  "controllers.Reverse*",
  "controllers.javascript.*",
  "jooq.*",
  "Module",
  "router.Routes*",
  "*.routes*"
)```

**Comment by erikthered** [comment]
That worked perfectly @stringbean, thanks for the help!

**Comment by NJ-Developer** [comment]
I want to exclude some packages from coverage report may anyone help with it.
for sbt.
