### ISSUE TITLE
How to configure unmanaged resource directory in sbt-jacoco 3.0.2?

### ISSUE THREAD

**Issue by vallim** [sbt/sbt-jacoco#97]
### Actual Behaviour

I was using the old version of jacoco over this configuration:

**_plugins.sbt_**
```
addSbtPlugin("de.johoop" % "jacoco4sbt" % "2.1.6")
```
**_build.sbt_**
```
...
jacoco.settings

unmanagedResourceDirectories in Test += baseDirectory.value / "test/resources"
unmanagedResourceDirectories in Compile += baseDirectory.value / "devops/cookbooks/thex_data_server/files/default/evolutions/default"
```
### Expected Behaviour

Now I'm migrating to use the jacoco over this configuration:

**_plugins.sbt_**
```
addSbtPlugin("com.github.sbt" % "sbt-jacoco" % "3.0.2")
```
**_build.sbt_**
```
My question is: what do I need put here to be able to recognize **unmanaged resource directories**?
```

### Environment

* SBT version: 0.13.5
* Plugin version: 3.0.2
* Scala version(s): 2.11.7
* Java version: 1.8.0

**Comment by stringbean** [comment]
sbt-jacoco should pick up the settings from the `Test` configuration so in your example:

```scala
unmanagedResourceDirectories in Test += baseDirectory.value / "test/resources"
unmanagedResourceDirectories in Compile += baseDirectory.value / "devops/cookbooks/thex_data_server/files/default/evolutions/default"
```

Should be sufficient. I've added a scripted test that shows a very simple example of this: [sbt-jacoco/unmanaged-resources](https://github.com/sbt/sbt-jacoco/tree/master/src/sbt-test/sbt-jacoco/unmanaged-resources)

**Comment by vallim** [comment]
Thanks @stringbean. It worked like a charm!
